### ISSUE TITLE
Output visualisation

### ISSUE THREAD

**Issue by Marion2** [raganmd/touchdesigner-sop-to-svg#12]
I followed the first example and when I open the SVG file in Inkspace I can only view an empty blank page like that : 

<img width="544" alt="Capture d’écran 2020-08-29 à 17 51 23" src="https://user-images.githubusercontent.com/25881733/91640881-0eb84880-ea21-11ea-87a9-3e2c474d58c0.png">

Is this normal ? Thanks for your help !

**Comment by Marion2** [comment]
I have the same issue with the second example and Axidraw isn't able to draw anything

**Comment by raganmd** [comment]
Hi @Marion2 - your SVG is actually in that first image, it's just very small in the upper right hand corner. You can use a transform SOP to make your SOP larger before converting to SVG, or you can resize in Inkscape.

I usually resize in inkscape or illustrator where I figure out my final layout before plotting.

**Comment by Marion2** [comment]
Thank you so much for your answer ! It worked !!

I have a last question for you : the only way for me to use this is to use the sop-to-svg tox from the "release folder" of your repo. If I try to duplicate it or take the base_sop_to_svg and paste it to a new project I have the following error on the svgEXT "No module named SVG write" and there is a terminal window that is opening. 

Is it normal ? Do you have some advices for me ?

**Comment by raganmd** [comment]
Hi @Marion2 - great question!

So the way this particular tox works is with an external python library called SVG Write. Inside of the tox from the release folder is a script that will do all the less exciting work of getting TouchDesigner to work with external python libraries.

What should happen is that in the same director as your project toe file, another folder called `dep` will be created, along with a sub folder called `python`. The terminal window that launches is attempting to do a pip install of the required external libraries into those directories, and then append TouchDesiger's sys path to include that newly added folder as a location for additional python libraries. 

Including the tox in a new project file should look like this:

* Create a new toe file in a directory somewhere on your computer.
* Save your toe file.
* Drag the tox from the release folder into your project.
* A few scripts should fire off and do all the installation work for you.
* At this point you may need to restart  your project file, but then you should be ready to create SVGs.

I usually work with one project file that's my SOP to SVG pipeline, and then pull in SOP networks from another toe file. I'll sometimes create my SOP network, then save it as a tox before bringing that into my SOP to SVG project file.

You can use the SOP to SVG tox in any project, you should just be aware that your toe file needs to be saved to a directory prior to dragging in the tox (otherwise TouchDesigner will attempt to install the dependent library to your desktop).

There's some debate in the community about the best approach for working with external libraries - I generally like them to travel with the project file as it makes it easier to move a whole folder rather than needing to go through the process of re-installing dependent libraries anytime you move to another computer. 

Hope that helps. :)

**Comment by Marion2** [comment]
That helps a lot ! Thank you for your explanations, I was able to do it right thanks to that 😄
